# Задача 1

In [4]:
import pandas as pd
df = pd.read_csv('ratings.csv')
def classification_films(rating):
    if rating <= 2:
        return 'низкий рейтинг'
    if 2 <=rating <= 4:
        return 'средний рейтинг'
    if rating >= 4.5:
        return 'высокий рейтинг'
df['class'] = df['rating'].apply(classification_films)
df.head()

   userId  movieId  rating  timestamp            class
0       1        1     4.0  964982703  средний рейтинг
1       1        3     4.0  964981247  средний рейтинг
2       1        6     4.0  964982224  средний рейтинг
3       1       47     5.0  964983815  высокий рейтинг
4       1       50     5.0  964982931  высокий рейтинг

# Задача 2

In [6]:
import pandas as pd
search_df = pd.read_csv('keywords.csv')
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}
def search_regions(keyword):
    for region, cities in geo_data.items():
        for city in cities:
            if city.lower() in keyword.lower():
                return region
            return 'undefined'
search_df['region'] = search_df['keyword'].apply(search_regions)
search_df.head()

         keyword     shows     region
0             вк  64292779  undefined
1  одноклассники  63810309  undefined
2          порно  41747114  undefined
3           ютуб  39995567  undefined
4      вконтакте  21014195  undefined

In [7]:
unique_values = search_df['region'].unique()   #проверка, что есть что-то кроме undefined
print(unique_values)

['undefined' 'Центр']